stages:
  - build

build-kernel:
  stage: build
  image: ubuntu:22.04
  timeout: 3h

  before_script:
    - apt update -y
    - apt install -y
        gcc-aarch64-linux-gnu
        gcc-arm-linux-gnueabi
        make bc libssl-dev
        libelf-dev bison flex
        git curl zip python3

  script:
    - echo "[+] Inject KSU Next..."
    - curl -LSs
        "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh"
        | bash -s next

    - echo "[+] Build kernel..."
    - export ARCH=arm64
    - export CROSS_COMPILE=aarch64-linux-gnu-
    - export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
    - make A125F_defconfig
    - scripts/config --disable MODULE_SIG_FORCE
    - make -j$(nproc)

    - echo "[+] Pack AnyKernel3..."
    - git clone --depth=1
        https://github.com/osm0sis/AnyKernel3 AK3
    - cp arch/arm64/boot/Image.gz-dtb AK3/
    - echo "kernel.string=Haruka-KSUNext-A125F" > AK3/anykernel.sh
    - echo "do.devicecheck=1" >> AK3/anykernel.sh
    - echo "device.name1=a12" >> AK3/anykernel.sh
    - echo "block=/dev/block/platform/bootdevice/by-name/boot" >> AK3/anykernel.sh
    - echo "is_slot_device=0" >> AK3/anykernel.sh
    - cd AK3 && zip -r9 ../Haruka-KSUNext-A125F.zip .

  artifacts:
    name: "Haruka-KSUNext-A125F"
    paths:
      - Haruka-KSUNext-A125F.zip
    expire_in: 7 days
